[theme]
base = "light"
primaryColor = "#E11D48"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#0F172A"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true

[server]
headless = true
maxUploadSize = 200
